// Shop-Produkte und Services (neutral, für i18n)
export const shopProducts = [
  {
    id: 'ebook-ai',
    type: 'ebook',
    image: 'https://images.pexels.com/photos/30530412/pexels-photo-30530412.jpeg',
    price: 19.99,
    key: 'shop.ebook.ai',
  },
  {
    id: 'ebook-marketing',
    type: 'ebook',
    image: 'https://images.pexels.com/photos/9034280/pexels-photo-9034280.jpeg',
    price: 14.99,
    key: 'shop.ebook.marketing',
  },
  {
    id: 'ebook-productivity',
    type: 'ebook',
    image: 'https://images.pexels.com/photos/6476808/pexels-photo-6476808.jpeg',
    price: 12.99,
    key: 'shop.ebook.productivity',
  },
  {
    id: 'ebook-startup',
    type: 'ebook',
    image: 'https://images.pexels.com/photos/3194521/pexels-photo-3194521.jpeg',
    price: 16.99,
    key: 'shop.ebook.startup',
  },
  {
    id: 'ebook-leadership',
    type: 'ebook',
    image: 'https://images.pexels.com/photos/7710087/pexels-photo-7710087.jpeg',
    price: 17.99,
    key: 'shop.ebook.leadership',
  },
  // Abo (Website Subscription Packages)
  {
    id: 'abo-basic',
    type: 'abo',
    image: 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg',
    price: 49,
    key: 'subs.basic',
    interval: 'month',
  },
  {
    id: 'abo-pro',
    type: 'abo',
    image: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg',
    price: 99,
    key: 'subs.pro',
    interval: 'month',
  },
  {
    id: 'abo-full',
    type: 'abo',
    image: 'https://images.pexels.com/photos/1181676/pexels-photo-1181676.jpeg',
    price: 199,
    key: 'subs.full',
    interval: 'month',
  },
  // Services
  {
    id: 'service-imagefilm',
    type: 'service',
    image: 'https://images.pexels.com/photos/3925161/pexels-photo-3925161.jpeg',
    price: 899,
    key: 'shop.service.imagefilm',
  },
  {
    id: 'service-socialclip',
    type: 'service',
    image: 'https://images.pexels.com/photos/10391808/pexels-photo-10391808.jpeg',
    price: 299,
    key: 'shop.service.socialclip',
  },
  {
    id: 'service-explain',
    type: 'service',
    image: 'https://images.pexels.com/photos/8088399/pexels-photo-8088399.jpeg',
    price: 499,
    key: 'shop.service.explain',
  },
  {
    id: 'service-werbevideo',
    type: 'service',
    image: 'https://images.pexels.com/photos/2443272/pexels-photo-2443272.jpeg',
    price: 799,
    key: 'shop.service.werbevideo',
  },
  {
    id: 'service-story',
    type: 'service',
    image: 'https://images.pexels.com/photos/6794837/pexels-photo-6794837.jpeg',
    price: 999,
    key: 'shop.service.story',
  },
];
